### ISSUE TITLE
What happens if this database exists?

### ISSUE THREAD

**Issue by leenux** [cockroachlabs-field/cockroachdb-remote-client#1]
Hi,
First thank you and your working.I am newbee for crdb.
My quest is:what happens if this database exists?

**Comment by timveil** [comment]
i've added `IF NOT EXISTS` language to the create statement so the create statement will be ignored if the database already exists.  Having said that, this client was designed with the assumption that the cluster and associated database would be frequently created and destroyed not "updated"
